### ISSUE TITLE
get_title only returns the DVD menu.

### ISSUE THREAD

**Issue by Cwavs** [Irrational-Encoding-Wizardry/vs-source#16] opened 2022-09-14 19:31 UTC
get_title seems to only be returning the9 frame long DVD menu and nothing else.
[VTS_01_0.IFO](http://www.cwavs.xyz/k1Twc7ceAqGjVS0L.IFO) I can provide other files from the DVD if need be as well.

**Comment by Cwavs** [comment] 2022-09-20 18:51
I've just found another DVD with the same issue, would you like samples from that one as well @Setsugennoao?

**Comment by Setsugennoao** [comment] 2023-10-15 13:21
Can't reproduce anymore. Issue is > 1year old so probably got fixed with the rewrite.

**Closed by Setsugennoao** 2023-10-15 13:21 UTC
